# ==============================
# WordPress-Omeka-Mysql: Secrets
# ==============================
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  rootpass: YWRtaW4=  # base64 encoded value of 'rootpass'
  username: d29yZHByZXNz # base64 encoded value of 'wordpress'
  password: d29yZHByZXNzcGFzcw== # base64 encoded value of 'wordpresspass'