# ===========================
# WordPress: Service
# ===========================
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  clusterIP: None
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80